LOG_PATH = './vsa2.log'

# App
APP_LISTEN = '0.0.0.0'
APP_PORT = '8866'

SUCCESS = "SUCCESS"
WARN = "WARN"
FAILED = "FAILED"

# Roles:
R_ADMIN = "admin"
R_USER_PHYSICAL = "physical"
R_USER_CLOUD = "cloud"

ALL_ROLES = [R_ADMIN, R_USER_PHYSICAL, R_USER_CLOUD]

# OpenStack
OPENSTACK_API_IP = '10.254.140.13'
OPENSTACK_KEYSTONE_PORT = '35357'
OPENSTACK_CINDER_PORT = '8776'
OPENSTACK_ADMIN_PASSWORD = '***'
OPENSTACK_PHYSICAL_PASSWORD = '***'
OPENSTACK_CLOUD_PASSWORD = '***'

# DB
DB_ENGINE = 'mariadb+pymysql'
DB_USERNAME = 'root'
DB_PASSWORD = '***'
DB_HOST = '10.254.140.13'
DB_PORT = '3306'
DB_NAME = 'vsa2'

# DCIM
DCIM_API = 'http://10.255.58.203/api/dcim/'
DCIM_TOKEN = '***'
